Update configure
add code to check python hosted packages.
dpkg error message be silent.

diff --git a/linux/config-script/configure b/linux/config-script/configure
--- a/linux/config-script/configure
+++ b/linux/config-script/configure
@@ -8,7 +8,7 @@ echo "check required packages: $REQUIREDS"
 
 for REQUIRED in $REQUIREDS ; do
     echo -n "checking required package $REQUIRED ... "
-    dpkg -l $REQUIRED | grep ^ii > /dev/null
+    dpkg -l $REQUIRED 2>&1 | grep ^ii > /dev/null
     if [ $? -ne 0 ]; then
         echo "[no]"
         echo "Please install required packages."
@@ -16,6 +16,24 @@ for REQUIRED in $REQUIREDS ; do
     fi
     echo "[yes]"
 done
+
+
+## Python3 hosted packages check.
+#
+#REQUIREDS="paho-mqtt"
+#echo
+#echo "check required python packages: $REQUIREDS"
+#
+#for REQUIRED in $REQUIREDS ; do
+#    echo -n "checking required package $REQUIRED ... "
+#    pip3 --quiet show $REQUIRED > /dev/null
+#    if [ $? -ne 0 ]; then
+#        echo "[no]"
+#        echo "Please run 'pip3 install $REQUIRED' to install required python package."
+#        exit 1
+#    fi
+#    echo "[yes]"
+#done
 
 
 echo -n "checking machine hardware ... "
@@ -32,10 +50,9 @@ SDKROOT=/opt/3rdSDK
 SDKINC=$SDKROOT/include
 SDKLIB=$SDKROOT/Linux/lib/$LIBARCH
 
- #### 
- # case 1.
- # If you have SDK of 3rd party, you want developer manual install it.
- # Are required files existence?
+## If you have SDK of 3rd party, you want developer manual install it.
+## Are required files existence?
+#
 #SDK_REQUIREDS="$SDKINC/sdk.h $SDKINC/sdk2.h $SDKLIB/sdk.so"
 #for REQUIRED in $SDK_REQUIREDS ; do
 #    echo -n "checking $REQUIRED ... "
@@ -47,7 +64,6 @@ SDKLIB=$SDKROOT/Linux/lib/$LIBARCH
 #        exit 1
 #    fi
 #done
-
 
 extract_tarball ()
 {
@@ -76,14 +92,15 @@ extract_tarball ()
     fi
 }
 
- #### 
- # case 2.
- # If you have SDK of 3rd party, you want download and extract it automatically.
- # Download and extract it.
+
+## If you have SDK of 3rd party, you want download and extract it automatically.
+## Download and extract it.
+#
 #wget http://localhost/3rdsdk/sdk.tar.gz
 #extract_tarball sdk.tar.gz src/sdk
 
-# Write variables to files.
+
+## Write variables to files.
 WRITEFILES="Makefile"
 for WRITEFILE in $WRITEFILES ; do
     echo -n "writting $WRITEFILE ... "
